version: '3.8'

services:
  lexio-ai:
    build: .
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./data:/app/data
    restart: unless-stopped